CITIES = {
    'מרכז': {
        'Tel Aviv - Yafo',
        'Petah Tiqwa',
        'Giv\'atayim',
        'Be\'er Ya\'aqov',
        'Qiryat Ono',
        'Ramla',
        'Bene Beraq',
        'Rosh HaAyin',
        'El\'ad',
        'Or Yehuda',
        'Ganne Tiqwa',
        'Bat Yam',
        'Lod',
        'Ramat Gan',
        'Modi\'in-Makkabbim-Re\'ut',
        'Rishon LeZiyyon',
        'Giv\'at Shemu\'el',
        'Yehud-Monoson',
        'Holon',
    },
    'שרון': {
        'Ra\'annana',
        'Qadima- Zoran',
        'Herzliyya',
        'Hod HaSharon',
        'Tel Mond',
        'Kefar Sava',
        'Kefar Yona',
        'Netanya',
    },
    'יהודה ושומרון ובקעת הירדן': {
        'Alfe Menashe',
        'Ari\'el',
        'Giv\'at Ze\'ev',
        'Immanu\'el',
        'Eli',
        'Qarne Shomeron',
        'Zur Yizhaq',
        'Betar Illit',
        'Avne Hefez',
        'Geva Binyamin',
        'Efrat',
        'Modi\'in Illit',
    },
    'חדרה, זכרון והעמקים': {
        'Ramat Yishay', 'Afula', 'Yoqne\'am Illit', 'Rekhasim', 'Bet She\'an',
        'Binyamina-Giv\'at Ada', 'Pardes Hanna-Karkur', 'Qiryat Tiv\'on', 'Zikhron Ya\'aqov',
        'Hadera', 'Or Aqiva', 'Harish'
    },
    'מחוז ירושלים': {
        'Zur Hadassa',
        'Bet Shemesh',
        'Ma\'ale Adummim',
        'Mevasseret Ziyyon',
        'Jerusalem',
    },
    'שפלה ומישור החוף הדרומי': {
        'Qiryat Gat',
        'Ashdod',
        'Sederot',
        'Rehovot',
        'Qiryat Mal\'akhi',
        'Qiryat Eqron',
        'Bene Ayish',
        'Gedera',
        'Yavne',
        'Ashqelon',
        'Nes Ziyyona',
    },
    'דרום': {
        'Dimona',
        'Elat',
        'Metar',
        'Be\'er Sheva',
        'Lehavim',
        'Yeroham',
        'Ofaqim',
        'Mizpe Ramon',
        'Arad',
        'Netivot',
    },
    'צפון': {
        'Qiryat Bialik',
        'Tiberias',
        'Qiryat Yam',
        'Nesher',
        'Migdal',
        'Akko',
        'Shelomi',
        'Qazrin',
        'Zefat',
        'Migdal HaEmeq',
        'Ma\'alot-Tarshiha',
        'Karmi\'el',
        'Qiryat Atta',
        'Qiryat Shemona',
        'Tirat Karmel',
        'Haifa',
        'Yavne\'el',
        'Nahariyya',
        'Nof HaGalil',
        'Qiryat Motzkin',
    }
}
